name: Deploy para Locaweb

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout do Código
        uses: actions/checkout@v4

      - name: Upload para FTP
        uses: SamKirkland/FTP-Deploy-Action@v3.1.1
        with:
          server: ${{ secrets.FTP_HOST }}
          username: ${{ secrets.FTP_USERNAME }}
          password: ${{ secrets.FTP_PASSWORD }}
          local-dir: "./"  # Diretório local
          server-dir: "/bosquinho/"  # Caminho no servidor
